services:
  expense-service:
    build:
      context: ./service
      dockerfile: docker/Dockerfile.spring-boot
    ports:
      - "9820:9820"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/expensiveservice 
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
      - mysql
    networks:
      - app-network

  auth-service:
    build:
      context: ./authservice
      dockerfile: docker/Dockerfile.spring-boot
    ports:
      - "9898:9898"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/authservice
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
      - mysql
    networks:
      - app-network

  user-service:
    build:
      context: ./userservice
      dockerfile: docker/Dockerfile.spring-boot
    ports:
      - "9810:9810"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/userservice
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
      - mysql
    networks:
      - app-network

  kafka:
    build:
      context: .
      dockerfile: Dockerfile.kafka
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/tmp/kraft-combined-logs
    networks:
      - app-network

  mysql:
    image: mysql:8.3.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - app-network

  kong:
    image: kong/kong-gateway:3.8.0.0
    container_name: kong
    restart: unless-stopped
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/etc/kong/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=http://localhost:8002
      - KONG_PROXY_LISTEN=0.0.0.0:8000
    ports:
      - "8000:8000" # Proxy port
      - "8001:8001" # Admin API
      - "8002:8002" # Kong Manager GUI
    volumes:
      - ./kong/kong.yml:/etc/kong/kong.yml:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql-data:
  kafka-data:

networks:
  app-network:
    driver: bridge
